spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/litangdb
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379