spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3306/litangdb
    username:
    password:

  data:
    redis:
      host:
      port: 6379
      password:

  rabbitmq:
    host:
    port: 5672
    username:
    password:
    virtual-host: